name: Prepare Prod Deploy
on:
  workflow_dispatch:
    inputs:
      ref:
        required: true
        description: Target GIT ref to deploy
        default: main
        type: string
jobs:
  prepare-deploy:
    name: Prepare deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref }}
      - name: Set vars
        id: vars
        run: |
          echo ::set-output name=release_name::$(git show -s --date=format:'%y.%m.%d-%H.%M.%S' --format=%cd)
      - name: Check if we should create a release
        id: should_create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if gh release view v${{ steps.vars.outputs.release_name }} --json 'id' 2>/dev/null ; then
            echo "Release v${{ steps.vars.outputs.release_name }} already exists"
            echo "::set-output name=should_create::false"
          else
            echo "Creating release v${{ steps.vars.outputs.release_name }}"
            echo "::set-output name=should_create::true"
          fi
      - name: Create draft release
        if: steps.should_create_release.outputs.should_create == 'true'
        run: gh release create v${{ steps.vars.outputs.release_name }} --title ${{ steps.vars.outputs.release_name }} --target $GITHUB_SHA --generate-notes --draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  call-deploy-prod-workflow:
    uses: ./.github/workflows/deploy-prod.yml
    needs: prepare-deploy
    if: needs.prepare-deploy.steps.should_create_release.outputs.should_create == 'false'
    with:
      ref: v${{ needs.prepare-deploy.outputs.release_name }}
    secrets: inherit

